name: Mobile Build

on:
  push:
    branches:
      - 'master'

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          min-wrapper-count: 1
          allow-snapshots: false

      - name: Fix Gradle wrapper permissions
        run: |
          chmod +x android/gradlew

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build Android Application
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon --warning-mode all

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-android
          path: android/app/build/outputs/apk/release/*.apk